# Generated by Django 5.1.7 on 2025-04-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitFair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='food_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
