# Generated by Django 5.1.7 on 2025-04-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitFair', '0002_meal_food_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='carbs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='fats',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='proteins',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
