# Generated by Django 5.1.7 on 2025-04-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitFair', '0003_meal_carbs_meal_fats_meal_proteins'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
