# Generated by Django 5.1.7 on 2025-04-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitFair', '0004_meal_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_of_the_day',
            field=models.CharField(blank=True, choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='total_calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
