# Generated by Django 5.1.7 on 2025-04-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitFair', '0006_alter_meal_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
