# Generated by Django 5.2 on 2025-04-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitFair', '0008_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fats',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='proteins',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='total_calories',
            field=models.FloatField(null=True),
        ),
    ]
