# Generated by Django 5.2 on 2025-04-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitFair', '0009_alter_meal_carbs_alter_meal_fats_alter_meal_proteins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_of_the_day',
            field=models.CharField(blank=True, choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snack', 'snack')], max_length=255, null=True),
        ),
    ]
